//
// Created by ahmed on 12/25/16.
//

#ifndef ENHANCEDUDPSERVER_GLOBALDEF_H
#define ENHANCEDUDPSERVER_GLOBALDEF_H


#define TIMEO_REDIRECT_MILLIS 20

#define TO_MILLISEC 1000
#define TIMEO_SEC 0
#define TIMEO_MICRO_SEC TO_MILLISEC * 5

#define LOSS_THRESH 0.6
#endif //ENHANCEDUDPSERVER_GLOBALDEF_H
